# CI/CD
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

# Author : Bayu Dwiyan Satria
# Contact : bayudwiyansatria@gmail.com / +62-823-9602-9583
# Site : https://www.bayudwiyansatria.com

name: 'Apache-Hadoop'

trigger: none
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Maven Build $(Build.BuildNumber)'
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven Test'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      LATEST_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
      curl -Ls -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-linux"
      chmod +x codacy-coverage-reporter
      ./codacy-coverage-reporter report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml